/** Reliable CDN icon URLs (devicon / vectorlogo) */

const d = (path: string) =>
  `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/${path}`;

export const skillIcons: { name: string; iconUrl: string }[] = [
  { name: "TypeScript", iconUrl: d("typescript/typescript-original.svg") },
  { name: "JavaScript", iconUrl: d("javascript/javascript-original.svg") },
  { name: "React", iconUrl: d("react/react-original-wordmark.svg") },
  { name: "Next.js", iconUrl: d("nextjs/nextjs-original.svg") },
  { name: "React Native", iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" },
  { name: "Node.js", iconUrl: d("nodejs/nodejs-original-wordmark.svg") },
  { name: "Express", iconUrl: d("express/express-original-wordmark.svg") },
  { name: "NestJS", iconUrl: d("nestjs/nestjs-original.svg") },
  { name: "Python", iconUrl: d("python/python-original.svg") },
  { name: "Django", iconUrl: d("django/django-plain.svg") },
  { name: "Flask", iconUrl: d("flask/flask-original.svg") },
  { name: "PostgreSQL", iconUrl: d("postgresql/postgresql-original.svg") },
  { name: "MongoDB", iconUrl: d("mongodb/mongodb-plain-wordmark.svg") },
  { name: "Redis", iconUrl: d("redis/redis-original.svg") },
  { name: "Prisma", iconUrl: d("prisma/prisma-original.svg") },
  { name: "Supabase", iconUrl: "https://www.vectorlogo.zone/logos/supabase/supabase-icon.svg" },
  { name: "GraphQL", iconUrl: d("graphql/graphql-plain.svg") },
  { name: "Tailwind CSS", iconUrl: "https://www.vectorlogo.zone/logos/tailwindcss/tailwindcss-icon.svg" },
  { name: "Sass", iconUrl: d("sass/sass-original.svg") },
  { name: "HTML5", iconUrl: d("html5/html5-original.svg") },
  { name: "CSS3", iconUrl: d("css3/css3-original.svg") },
  { name: "Bootstrap", iconUrl: d("bootstrap/bootstrap-original.svg") },
  { name: "Redux", iconUrl: d("redux/redux-original.svg") },
  { name: "MobX", iconUrl: d("mobx/mobx-original.svg") },
  { name: "Ant Design", iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/antdesign/ant-design-original.svg" },
  { name: "Material UI", iconUrl: d("materialui/materialui-original.svg") },
  { name: "shadcn/ui", iconUrl: "https://avatars.githubusercontent.com/u/139895814?s=200&v=4" },
  { name: "Vite", iconUrl: d("vite/vite-original.svg") },
  { name: "Docker", iconUrl: d("docker/docker-original.svg") },
  { name: "AWS", iconUrl: d("amazonwebservices/amazonwebservices-plain-wordmark.svg") },
  { name: "DigitalOcean", iconUrl: d("digitalocean/digitalocean-original.svg") },
  { name: "Firebase", iconUrl: d("firebase/firebase-plain.svg") },
  { name: "Git", iconUrl: d("git/git-original.svg") },
  { name: "GitLab", iconUrl: d("gitlab/gitlab-original.svg") },
  { name: "Stripe", iconUrl: d("stripe/stripe-original.svg") },
  { name: "Medusa.js", iconUrl: "https://avatars.githubusercontent.com/u/59018053?s=200&v=4" },
  { name: "Cloudinary", iconUrl: "https://www.vectorlogo.zone/logos/cloudinary/cloudinary-icon.svg" },
  { name: "Vercel", iconUrl: d("vercel/vercel-original.svg") },
  { name: "Expo", iconUrl: "https://www.vectorlogo.zone/logos/expoio/expoio-icon.svg" },
  { name: "Socket.io", iconUrl: "https://www.vectorlogo.zone/logos/socketio/socketio-icon.svg" },
  { name: "Playwright", iconUrl: d("playwright/playwright-original.svg") },
  { name: "Postman", iconUrl: "https://www.vectorlogo.zone/logos/getpostman/getpostman-icon.svg" },
  { name: "Figma", iconUrl: d("figma/figma-original.svg") },
  { name: "VS Code", iconUrl: d("vscode/vscode-original.svg") },
  { name: "Linux", iconUrl: d("linux/linux-original.svg") },
  { name: "NGINX", iconUrl: d("nginx/nginx-original.svg") },
  { name: "Kafka", iconUrl: "https://www.vectorlogo.zone/logos/apache_kafka/apache_kafka-icon.svg" },
];

export const serviceIcons: Record<string, string> = {
  "Web Application Development": d("react/react-original-wordmark.svg"),
  "Mobile Application Development": "https://www.vectorlogo.zone/logos/expoio/expoio-icon.svg",
  "Backend & API Engineering": d("nodejs/nodejs-original-wordmark.svg"),
  "SaaS & Multi-tenant Systems": d("graphql/graphql-plain.svg"),
  "Cloud, DevOps & Integrations": d("docker/docker-original.svg"),
  "AI & Real-time Features": d("python/python-original.svg"),
};
